name       : ffmpegthumbnailer
version    : 2.2.2
release    : 10
source     :
    - https://github.com/dirkvdb/ffmpegthumbnailer/releases/download/2.2.2/ffmpegthumbnailer-2.2.2.tar.bz2 : 1cb24059c38223f657b300c84dd80491b7040d4b69471c4fea69be862bc99b5b
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : Lightweight video thumbnailer that can be used by file managers
description: |
    FFmpegthumbnailer is a lightweight video thumbnailer that can be used by file managers to create thumbnails for your video files. The thumbnailer uses ffmpeg to decode frames from the video files, so supported videoformats depend on the configuration flags of ffmpeg.
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
setup      : |
    %cmake -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON
build      : |
    %make
install    : |
    %make_install
