name       : ffmpegthumbnailer
version    : 2.2.0
release    : 3
source     :
    - https://github.com/dirkvdb/ffmpegthumbnailer/releases/download/2.2.0/ffmpegthumbnailer-2.2.0.tar.bz2 : e5c31299d064968198cd378f7488e52cd5e738fac998eea780bc77d7f32238c2
license    : GPL-2.0
component  : multimedia.library
summary    : Lightweight video thumbnailer that can be used by file managers.
description: |
    FFmpegthumbnailer is a lightweight video thumbnailer that can be used by file managers to create thumbnails for your video files. The thumbnailer uses ffmpeg to decode frames from the video files, so supported videoformats depend on the configuration flags of ffmpeg.
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - libjpeg-turbo-devel
setup      : |
    %cmake -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON
build      : |
    %make
install    : |
    %make_install
