name        : ffmpegthumbnailer
version     : 2.1.1
release     : 2
source      :
    - https://github.com/dirkvdb/ffmpegthumbnailer/archive/2.1.1.tar.gz : e43d8aae7e80771dc700b3d960a0717d5d28156684a8ddc485572cbcbc4365e9
license     : GPL-2.0
component   : multimedia.library
summary     : Lightweight video thumbnailer that can be used by file managers.
description : |
    FFmpegthumbnailer is a lightweight video thumbnailer that can be used by file managers to create thumbnails for your video files. The thumbnailer uses ffmpeg to decode frames from the video files, so supported videoformats depend on the configuration flags of ffmpeg.
builddeps   :
    - pkgconfig(libavcodec)
    - pkgconfig(libpng)
    - libjpeg-turbo-devel
setup      : |
    %cmake -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON
build      : |
    %make
install    : |
    %make_install
